database:
  host: localhost
  port: 6379
  database: mnemosyne
  connection_pool_size: 10
  connection_timeout: 30
  query_timeout: 60

api:
  host: 0.0.0.0
  port: 8000
  grpc_port: 50051
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  cors_allow_credentials: true
  cors_allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_allow_headers:
    - "*"

logging:
  level: INFO
  format: json
  handlers:
    - type: console
      level: INFO
    - type: file
      level: DEBUG
      filename: logs/mnemosyne.log
      max_bytes: 10485760
      backup_count: 5

security:
  secret_key: dev-secret-key-change-in-production
  api_key_header: X-API-Key

environment: development

features:
  enable_metrics: false
  metrics_port: 9090
  enable_tracing: false
  enable_debug_queries: true
