name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      falkordb:
        image: falkordb/falkordb:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        pipx install uv
    
    - name: Install dependencies
      run: |
        uv pip install --system -e ".[dev]"

    - name: Run linting
      run: |
        python -m black --check src tests || true
        python -m isort --check-only src tests || true
        python -m flake8 src tests --max-line-length=88 --extend-ignore=E203,W503 || true
    
    - name: Run tests
      env:
        FALKORDB_HOST: localhost
        FALKORDB_PORT: 6379
        FALKORDB_DATABASE: test_mnemosyne
        PYTHONPATH: src
      run: |
        python -m pytest tests/unit/ -v --no-cov
    

